# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_auto_20180110_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogsite.Reccommended_Book'),
        ),
    ]
