# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='yeet'),
            preserve_default=False,
        ),
    ]
