# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_auto_20180110_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='reccommended_book',
            name='author',
            field=models.CharField(default='Lorem Ipsum', max_length=50),
            preserve_default=False,
        ),
    ]
