# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0003_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpost',
            name='genre',
            field=models.CharField(default='da', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='Post_Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
