# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0004_reccommended_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reccommended_book',
            name='Book_Image',
            field=models.ImageField(blank=True, upload_to='post_imgs/'),
        ),
    ]
