# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0004_auto_20180104_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReccommendedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='Post_Image',
            field=models.ImageField(blank=True, upload_to='post_imgs/'),
        ),
    ]
