# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0005_reccommended_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reccommended_book',
            name='Buy_Link',
            field=models.CharField(blank=True, max_length=2083),
        ),
    ]
