# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0006_auto_20180109_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 9, 12, 45, 53, 285345)),
        ),
    ]
