# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0007_post_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='credits',
            field=models.TextField(blank=True),
        ),
    ]
