# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0008_auto_20180109_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 9, 12, 48, 34, 160414)),
        ),
    ]
