# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0002_auto_20180120_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_Image',
            field=models.ImageField(blank=True, null=True, upload_to='post_imgs/'),
        ),
        migrations.AlterField(
            model_name='reccommended_book',
            name='Book_Image',
            field=models.ImageField(upload_to='post_imgs/'),
        ),
    ]
